### ISSUE TITLE
How did you like Zircon?

### ISSUE THREAD

**Issue by bruce-forte** [niksaz/spbau-software-design#5]
Hey. I searched for Zircon on GitHub and I bumped into your project. I was wondering how did you like the lib. I'm looking for feedback on the project.

**Comment by niksaz** [comment]
Hi, @adam-arold. Thanks for developing the library!
I enjoyed using it. It was for a small homework project that included developing a game with text UI.
I have not used all features for sure. But the ramp-up time was negligible since the library is on part with other major GUI libraries. It integrated well into Scala project. I loved the overlays system that allowed to spread drawing code across several independent classes. You have an extensive number of ready-to-use Widgets that was a huge plus for me.
One thing that could be beneficial is having layouts because I did all the widget placing myself. But I could also see it not being that useful in text GUI games.
Also huge thanks for your wiki-page!

**Comment by bruce-forte** [comment]
I just retrofitted the Wiki page and the README for the new version which is coming in Autumn. Layouts are something which were asked for before so we'll have `HBox` and `VBox` soon for starters.

How did you find Zircon? I saw that some other students (?) also did the same homework assignment but I was not able to figure out how did you choose Zircon. Care to elaborate a bit?

**Comment by niksaz** [comment]
Oh, nice.

It was part of the problem to create a game with text GUI. Zircon was the only option I found that provided easy-to-use interface to text GUI, looked modern and had extensive documentation.

**Comment by bruce-forte** [comment]
Did you find it on your own or did you work together with others? Glad to hear that you liked the interface. If you bump into something which you think can be improved feel free to [create an issue](https://github.com/Hexworks/zircon/issues/new) about it on our issue tracker.

**Comment by niksaz** [comment]
Sure.
Not really working with others -- just google searched it.

**Comment by bruce-forte** [comment]
Thanks for the info this really helps! If you'll have questions in the future feel free to come up to our [Discord Server](https://discord.gg/UhdhBff).
